util.AddNetworkString("BobTheBuilder")
util.AddNetworkString("Kit_BobTheBuilder")
util.AddNetworkString("KitCollect")
net.Receive("KitCollect", function(len, pl)
    local str = net.ReadString()
    local inv = pl:GetInventory()
    if str == "Kit Builder" and not pl:GetPData("CollectedBuilder",false) then
        local Wood = gRust.CreateItem("wood")
        Wood:SetQuantity(100000)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("metal_fragments")
        Wood:SetQuantity(100000)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("furnace")
        Wood:SetQuantity(1)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("large_wood_box")
        Wood:SetQuantity(1)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("building_plan")
        Wood:SetQuantity(1)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("hammer")
        Wood:SetQuantity(1)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("sheet_metal_double_door")
        Wood:SetQuantity(1)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("key_lock")
        Wood:SetQuantity(2)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("sleeping_bag")
        Wood:SetQuantity(1)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("workbench_level_1")
        Wood:SetQuantity(1)
        inv:Set(inv:FirstEmpty(), Wood)
        pl:SetPData("CollectedBuilder",true)
    end

    if str == "Kit Starter" and not pl:GetPData("Collected2",false)  then
        local Wood = gRust.CreateItem("hunting_bow")
        Wood:SetQuantity(2)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("arrow")
        Wood:SetQuantity(30)
        inv:Set(inv:FirstEmpty(), Wood)
        local Wood = gRust.CreateItem("medical_syringe")
        Wood:SetQuantity(2)
        inv:Set(inv:FirstEmpty(), Wood)
        pl.Collected2 = true
         pl:SetPData("Collected2",true)
    end
end)